# Generated by Django 3.2 on 2024-11-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_hitmen_mobilenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitmen',
            name='otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
